<a href="https://colab.research.google.com/github/fyr-repo/parallel_programming_intro/blob/main/matrix_mul_tf_gpu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
import numpy as np
import time

In [10]:
# Define the dimensions and values of the arrays
rows_cols = 1000
value = 55.55

# Create the input arrays filled with the specified value
array1 = tf.constant([[value] * rows_cols] * rows_cols, dtype=tf.float32)
array2 = tf.constant([[value] * rows_cols] * rows_cols, dtype=tf.float32)

# Measure the start time
start_time = time.time()

# Perform matrix multiplication
result = tf.matmul(array1, array2)

# Measure the end time
end_time = time.time()

# Calculate the time taken for processing
processing_time = end_time - start_time

# Print the result and time taken for processing
print("Matrix multiplication result:")
print(result)
print(f"Time taken for processing: {processing_time:.4f} seconds")


Matrix multiplication result:
tf.Tensor(
[[3085807.2 3085807.2 3085807.2 ... 3085807.2 3085807.2 3085807.2]
 [3085807.2 3085807.2 3085807.2 ... 3085807.2 3085807.2 3085807.2]
 [3085807.2 3085807.2 3085807.2 ... 3085807.2 3085807.2 3085807.2]
 ...
 [3085807.2 3085807.2 3085807.2 ... 3085807.2 3085807.2 3085807.2]
 [3085807.2 3085807.2 3085807.2 ... 3085807.2 3085807.2 3085807.2]
 [3085807.2 3085807.2 3085807.2 ... 3085807.2 3085807.2 3085807.2]], shape=(1000, 1000), dtype=float32)
Time taken for processing: 0.0010 seconds
